version: '3'

services:
  elastalert:
    build:
      context: elastalert/
    container_name: elastalert

    ports:
      - '3030:3030'
      - '3333:3333'
    environment:
     - PRAECO_ELASTICSEARCH=${PRAECO_ELASTICSEARCH}
    volumes:
      - ./config/elastalert.yaml:/opt/elastalert/config.yaml
      - ./config/api.config.json:/opt/elastalert-server/config/config.json
      - ./rules:/opt/elastalert/rules
      - ./rule_templates:/opt/elastalert/rule_templates

    extra_hosts:
      - 'elasticsearch:${PRAECO_ELASTICSEARCH}'

  webapp:
    build:
      context: webapp/
    container_name: webapp
    ports:
      - '8080:8080'
    environment:
     - PRAECO_ELASTICSEARCH=${PRAECO_ELASTICSEARCH}
    volumes:
      - ./public/praeco.config.json:/var/www/html/praeco.config.json
      - ./nginx_config/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx_config/default.conf:/etc/nginx/conf.d/default.conf
