

# https://github.com/elastic/elasticsearch-docker
FROM servercentral/elastalert

ENV TZ=America/Santiago
RUN PRAECO_ELASTICSEARCH=${PRAECO_ELASTICSEARCH}
#RUN apt-get update -y
#RUN apt-get install nano -y

# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu