

# https://github.com/elastic/elasticsearch-docker
FROM servercentral/elastalert

RUN apt-get update -y
RUN apt-get install nano -y

# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu